### ISSUE TITLE
Building it on mac

### ISSUE THREAD

**Issue by donmurdoc** [norihiro/obs-command-source#1]
Hi, I'm trying to do this, but I get this error and don't know what to do exactly:

I run the cmake, but get this error:

> cmake /Users/mynameis/Downloads/obs-command-source-master
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBOBS_INCLUDE_DIR
   used as include directory in directory /Users/mynameis/Downloads/obs-command-source-master
   used as include directory in directory /Users/mynameis/Downloads/obs-command-source-master
   used as include directory in directory /Users/mynameis/Downloads/obs-command-source-master
   used as include directory in directory /Users/mynameis/Downloads/obs-command-source-master
   used as include directory in directory /Users/mynameis/Downloads/obs-command-source-master
   used as include directory in directory /Users/mynameis/Downloads/obs-command-source-master
   used as include directory in directory /Users/mynameis/Downloads/obs-command-source-master
OBS_LIBRARIES
    linked by target "command-source" in directory /Users/mynameis/Downloads/obs-command-source-master

-- Configuring incomplete, errors occurred!
See also "/Users/mynameis/Downloads/caca/CMakeFiles/CMakeOutput.log".

**Comment by norihiro** [comment]
Hi,
Thank you for trying this plugin.
I'm afraid you need to set `LIBOBS_INCLUDE_DIR` to point the location that contains header files such as `obs-module.h`.
`cmake -DLIBOBS_INCLUDE_DIR=..../obs-studio/libobs  ..`

**Comment by donmurdoc** [comment]
ok, I know the dir.
Now, where should I put that info?

**Comment by donmurdoc** [comment]
Ok I get it.
Now I got this error:

WARNING: Target "command-source" requests linking to directory "/Applications/OBS.app/Contents/Resources/data/libobs".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to:

**Comment by donmurdoc** [comment]
I guess the libobs binary is somewhere else? (I'm sorry I'm not a programer)

**Comment by donmurdoc** [comment]
This is the command I executed:

> cmake -DLIBOBS_INCLUDE_DIR=/Applications/OBS.app/Contents/Resources/data/libobs -DOBS_LIBRARIES=/Applications/OBS.app/Contents/Resources/data/libobs /Users/mynameis/Downloads/obs-command-source-master

**Comment by norihiro** [comment]
I've rewritten build script based on another plugin `obs-ndi`. You can download pkg from [release section](https://github.com/norihiro/obs-command-source/releases).
