### ISSUE TITLE
"Shown In Preview" command is not triggered when the source is inside a Group

### ISSUE THREAD

**Issue by poelguedj** [norihiro/obs-command-source#19]
Hello 
In OBS, I am in "_studio mode_" with a scene containing (among others sources...) a _Group_, and inside that group, there is an _obs-command-source_ named **Execute command**
In the properties of that source I have  a command  (an microsoft windows command  **MSG ...** just for testing) in the field _Shown in Preview_.
But, when I click on the eye of the source to activate it in the preview, the command **MSG...** is not triggered

It works well when the _obs-command-source_ is not in a _group_ inside the scene so the problem is related to the fact that the source is inside a group

**Comment by norihiro** [comment]
Thank you for your report. I was not considering the case that the user changes the visibility.

**Comment by norihiro** [comment]
Close this ticket since the bug belong to the upstream and there is nothing I can do in this plugin.
