### ISSUE TITLE
Sending Signal seems not working in 0.3.1

### ISSUE THREAD

**Issue by eribertomota** [norihiro/obs-command-source#22]
Dear @norihiro,

I added "xcalc" at "Activated" and I set "Send signal to the command at activated when deactivating". I am using "SIGTERM". The xcalc is shown after the transition from "Preview" to "Program". However, the process keeps alive when the transition is made again and the scene returns to Preview.

Thanks!

**Comment by norihiro** [comment]
I cannot reproduce it with xcalc on Fedora 36.
Is `xcalc` on your host a script or executable? The implementation is just sending a signal to the PID that was created by this plugin. If `xcalc` command is a script and executing another executable of `xcalc`, the PID could change and cannot kill it.

**Comment by eribertomota** [comment]
$ file /usr/bin/xcalc 
/usr/bin/xcalc: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d1bc7ce9b99ff3d667f13e5f9701c2411fa23236, for GNU/Linux 3.2.0, stripped

This is an executable compiled by GCC, not a script. The xcalc is a dependence for x11-apps  on Debian (Testing). So, when installing XOrg, the xcalc will be installed too.

**Comment by norihiro** [comment]
If I add a redirect `&>/dev/null`, I can reproduce the issue though I'm still not 100% certain this reproduces the same issue.
The shell has a subprocess like below and this plugin sends the signal to `sh` (PID `63342`) so that the actual `xcalc` is not killed.
```
$ ps ax | grep xcalc
  63342 pts/9    S+     0:00 sh -c xcalc &>/dev/null
  63343 pts/9    S+     0:00 xcalc
```

Maybe this plugin should send the signal to the grandchildren.

**Comment by eribertomota** [comment]
> ~Maybe this plugin should send the signal to the grandchildren.~ A solution I'm thinking of is calling `setpgid(pid, 0)` after the fork and use `killpg` instead of `kill`.

I am available to test any PR created from you.

**Comment by norihiro** [comment]
I've created a PR that tries to solve this issue. Would you test with my PR?

Also added debug log. If not working, would you try these steps to investigate further?
1. Run OBS Studio with `obs --verbose`
2. Start `xcalc` through this plugin
3. Check some info of `xcalc`
4. Try to kill `xcalc` through this plugin
   ```
   ps -a -o pid,pgid,command | grep xcalc
   ```
5. Check log file (will be printed to stdout)

**Comment by eribertomota** [comment]
Hi @norihiro,

I applied all changes made today (986afce, 95bb895 and 6c47ec0). After this, I applied the PR and the plugin worked fine with xcalc. IMO, this issue is solved. Do you need more tests?

**Comment by norihiro** [comment]
Thank you so much for your testing. I will create a new release.

**Comment by eribertomota** [comment]
Good! I will package 0.4.0 and send to Debian now.

**Comment by eribertomota** [comment]
Hi @norihiro, 

To avoid to open a new issue, I will take advantage of this place. Yesterday I sent a new package to Debian. However, I forgot to check for changes in licensing. So, today, I sent a new revision because the GPL-3+ for two files. I noticed that LICENSING file remains using GPL-2. Is this right or was a mistake? This is a check only, not a problem. Thanks!

**Comment by norihiro** [comment]
Thank you for your notification. GPL2+ is my intended copyright. I have to update the comment.
