### ISSUE TITLE
Please, drop rpath (I need this for Debian)

### ISSUE THREAD

**Issue by eribertomota** [norihiro/obs-command-source#27]
Hi @norihiro,

I finished the packaging of the obs-command-source for Debian. Lintian (the packaging checker tool) shows an Error and it is impeditive to send the package.

`
E: obs-command-source: custom-library-search-path RUNPATH /usr/lib [usr/lib/x86_64-linux-gnu/obs-plugins/command-source.so]
`

There is an explanation about this issue here[1].

[1] https://lintian.debian.org/tags/custom-library-search-path

Could you check this?

Just for curiosity, the packaging is available here[2].

[2] https://salsa.debian.org/eriberto/obs-command-source

Thanks in advance.

**Comment by eribertomota** [comment]
Note you don't need to release a new version only for this change. I am able to apply a patch in my package.

**Comment by eribertomota** [comment]
I remembered about a similar issue in advanced-scene-switch. The discussion about this maybe helps you. Please, see here[1][2].

[1] https://github.com/WarmUpTill/SceneSwitcher/issues/548
[2] https://github.com/WarmUpTill/SceneSwitcher/pull/554

**Comment by norihiro** [comment]
I appreciate your packaging this plugin for Debian and your feedback.
The RPATH setting comes from obs-plugintemplate. You might see the same issues if you are packaging other plugins.
https://github.com/obsproject/obs-plugintemplate/blob/86ae5b4de6454ce42f8ce471054faa34ef66fef0/cmake/ObsPluginHelpers.cmake#L490

**Comment by eribertomota** [comment]
Thanks for your attention. I will send the package to Debian in few minutes.

About the RPATH, several upstreams like exeldro, Warmuptill and Ashmanix are naturally dropping it for all plugins.

Have a nice day!
