### ISSUE TITLE
Build in tree on Linux

### ISSUE THREAD

**Issue by ogmkp** [norihiro/obs-command-source#29]
Hi.

How to build in tree on Linux, especially Debian 11 Bullseye ?

Thanks !

**Comment by norihiro** [comment]
This plugin does not support to build in tree.
Is there any particular reason to build in tree?

**Comment by ogmkp** [comment]
Yes, all plugins are bundled to one package and saves time on building consistency.
Like @exeldro repos, It will be great if I can build in tree all your obs projects ;)

**Comment by norihiro** [comment]
I quickly test [obsproject/obs-plugintemplate](https://github.com/obsproject/obs-plugintemplate) to build in tree and it failed.
I blame this issue comes from obsproject/obs-plugintemplate.

**Comment by ogmkp** [comment]
Ok, I still on standalone plugins fow now, if this evolves, I still interrested, thank you for yours projetcs !

**Comment by norihiro** [comment]
I'm sorry that I'm not good at writing cmake. I just copied cmake files from the template and modified it slightly.
