### ISSUE TITLE
obs-command-source 0.1.2 not loaded by OBS-Studio 25.0.8 on mac ?

### ISSUE THREAD

**Issue by XReyRobert** [norihiro/obs-command-source#8]
Hi There,
I can't manage to load the plugin on obs 25.0.8 (Mac)...  no trace in obs log.

**Comment by norihiro** [comment]
I can reproduce the problem with OBS Studio 26.0.2 on MacOS.
The file name `command-souce.so` should be `obs-command-souce.so`. I will fix it.
For now, you can rename the file in `/Library/Application Support/obs-studio/plugins/obs-command-source/bin`.

**Comment by norihiro** [comment]
Thank you for interesting this plugin and reporting the issue.
The updated plugin is released as `0.1.4`.
